# Generated by Django 5.0.2 on 2024-03-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
